export const buttons = [
    {val: 'AC', className: ''},
    {val: '+/-', className: ''},
    {val: '%', className: ''},
    {val: '/', className: 'orange'},
    {val: '7', className: ''},
    {val: '8', className: ''},
    {val: '9', className: ''},
    {val: 'x', className: 'orange'},
    {val: '4', className: ''},
    {val: '5', className: ''},
    {val: '6', className: ''},
    {val: '-', className: 'orange'},
    {val: '1', className: ''},
    {val: '2', className: ''},
    {val: '3', className: ''},
    {val: '+', className: 'orange'},
    {val: '0', className: 'span-2'},
    {val: '.', className: ''},
    {val: '=', className: 'orange'},
]